global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:80"]

  - job_name: "web"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:3000"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb:27017"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]